aws/aperf

- src/data/kernel_config.rs
- src/data/perf_stat.rs
- src/data/systeminfo.rs
Also,
* use WARN in Perf Stat when asking to change system settings.
* use WARN in SystemInfo when IMDS fails.
> Record: Handle Kernel config not available

- src/html_files/cpu_utilization.ts
- src/html_files/disk_stats.ts
- src/html_files/flamegraphs.ts
- src/html_files/index.css
- src/html_files/index.html
- src/html_files/index.ts
- src/html_files/interrupts.ts
- src/html_files/kernel_config.ts
- src/html_files/meminfo.ts
- src/html_files/netstat.ts
- src/html_files/perf_profile.ts
- src/html_files/perf_stat.ts
- src/html_files/processes.ts
- src/html_files/sysctl.ts
- src/html_files/system_info.ts
- src/html_files/vmstat.ts
- src/report.rs
Move to a Grid layout for the report. Remove code that creates header for each tab. Instead, create a header once and pin it to the top. The headers will also show when scrolling.
> Report: Refactor code, use CSS grid layout

- README.md
On Ubuntu with c7g, the path is /sys/devices/armv8_pmuv3_0/... however on other systems, it's  /sys/devices/cpu/... Accommodate both of these and others by globbing that whole directory as "*"
> Readme: Update perf_event_mux_interval instructions

- README.md
Perfrunbook location changed in https://github.com/aws/aws-graviton-getting-started/commit/a834d804f363ec7cb4fd5b716bf2310cfc3955c8
*Issue #, if available:*
> Update Perfrunbook location

- src/data/processes.rs
- src/report.rs
Before, the ```--help``` message didn't indicate multiple ```-r``` arguments could be supplied to ```report```
```
[ec2-user@ip-10-0-0-129 ~]$ ./aperf report --help
Generate an HTML report based on the data collected
Usage: aperf report [OPTIONS]
Options:
-r, --run <RUN>    Run data to be visualized. Can be a directory or a tarball
-n, --name <NAME>  Report name
-v, --verbose...   Show debug messages. Use -vv for more verbose messages
-h, --help         Print help
-V, --version      Print version
```
and moreover, you didn't even have to specify any. Doing so would get you an empty report (not very useful).
```
[ec2-user@ip-10-0-0-129 aperf]$ ./target/debug/aperf report -n foo
[2024-04-08T14:54:05Z INFO  aperf_lib::report] Creating APerf report...
[2024-04-08T14:54:05Z INFO …
```
> Make -r argument to 'report' required and improve usage message

- src/data/perf_stat.rs
When I ran the tests on a codebuild github runner (I don't actually know the instance type because they don't let you choose), this test was failing. I modified it to dump the event keys, and the failure was because ```data-st-tlb-mpki``` and ```data-st-tlb-tw-pki``` were being returned, but hadn't been added to this test's allow-list.
The values that the test failure saw
```
Event values: ["ipc", "stall-frontend-pkc", "branch-mpki", "inst-tlb-mpki", "inst-tlb-tw-pki", "inst-l1-mpki", "stall-backend-pkc", "l3-mpki", "l2-mpki", "data-tlb-mpki", "data-tlb-tw-pki", "data-l1-mpki", "data-st-tlb-mpki", "data-st-tlb-tw-pki", "ipc", "stall-frontend-pkc", "branch-mpki", "inst-tlb-mpki", "inst-tlb-tw-pki", "inst-l1-mpki", "stall-backend-pkc", "l3-mpki", "l2-mpki", "data-tlb-mpki", …
```
> test_get_named_events: Don't try and maintain the set of all possible perf stat keys here.

- src/data.rs
- src/data/perf_profile.rs
- src/lib.rs
The time taken by perf record after the collection period depends on the time of collection and the system load. On heavily loaded systems, profiling can take longer than the time it takes to go from perf collection to perf inject in the post collection step. To prevent a race condition, add a wait before the perf inject step.
> Wait for 'perf record' to finish

- Cargo.lock
- Cargo.toml
- build.rs
- src/bin/aperf.rs
- src/lib.rs
This allows for building from the source tarball. Previously, the build system expected to be executed from a git repository to emit a GIT SHA. Remove this requirement with vergen v8.3 which emits a default value if a GIT SHA cannot be identified.
Tested by getting the source tarball from the `vergen` branch and building it.
> Move to vergen 8.3

- src/data.rs
- src/data/aperf_stats.rs
- src/html_files/aperf_run_stats.ts
- src/html_files/index.html
- src/html_files/index.ts
- src/html_files/utils.ts
- src/lib.rs
Collect the time it takes the various aperf data types to gather the data and print them to a file. This also adds a tab in the report.
[aperf_report_stats.tar.gz](https://github.com/user-attachments/files/15888403/aperf_report_stats.tar.gz)
> Add Aperf Stats

- src/data/flamegraphs.rs
- src/data/java_profile.rs
- src/data/perf_profile.rs
- src/visualizer.rs
Currently, users are unable to generate reports, of an aperf run with --profile, on a system that is not the SUT. Move the processing step for perf_profile and flamegraph to the record stage.
Testing:
Prior to this change, it was not possible to generate a comparison of profiling between runs in arm64 and x86.
[arm64profile.tar.gz](https://github.com/user-attachments/files/16275219/arm64profile.tar.gz)
[x86profile.tar.gz](https://github.com/user-attachments/files/16275220/x86profile.tar.gz)
[profilecmp.tar.gz](https://github.com/user-attachments/files/16275221/profilecmp.tar.gz)
> Move profiling processing to the record step

- src/record.rs
If aperf record is run with sudo and exits without cleaning up its temp folder, future non-sudo aperf records will fail to create this folder and panic. This error message informs the user of the error, and how to remove the existing folder with root permissions.
Added error check and message when aperf record creates the aperf_tmp folder.
Tested with existing tmp folder with different permissions. When aperf is unable to create the folder it displays this error message:
```
[2024-07-26T17:05:38Z ERROR aperf_lib::record] Could not create /tmp/aperf_tmp folder.
File exists (os error 17): Remove using 'sudo rm -rf /tmp/aperf_tmp'.
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Add error message for fail to create record temp folder

- Cargo.lock
- Cargo.toml
- src/data.rs
- src/data/java_profile.rs
- src/data/perf_profile.rs
- src/lib.rs
This is used if the user ends an Aperf run using Ctrl+c or kill <pid>.
Ran aperf record and ctrl-c'd:
$ ./target/debug/aperf record -r ctrlcrecord
[2024-07-25T15:37:59Z INFO  aperf_lib::record] Starting Data collection...
[2024-07-25T15:37:59Z INFO  aperf_lib::record] Preparing data collectors...
[2024-07-25T15:37:59Z WARN  aperf_lib::data::perf_stat] Instance does not expose Perf counters
[2024-07-25T15:37:59Z ERROR aperf_lib] Excluding perf_stat from collection. Error msg: No such file or directory (os error 2)
[2024-07-25T15:37:59Z INFO  aperf_lib::record] Collecting data...
^C[2024-07-25T15:38:01Z INFO  aperf_lib] Caught SIGINT. Exiting...
[2024-07-25T15:38:02Z INFO  aperf_lib] Data collected in ctrlcrecord/, archived in ctrlcrecord.tar.gz
[2024-07-25T15:38:02Z INFO …
> Add support for catching signals

- src/data.rs
- src/data/amd_genoa_perf_events.rs
- src/data/amd_milan_perf_events.rs
- src/data/amd_perf_events.rs
- src/data/perf_stat.rs
- Added AMD PMU event numbers and support in `perf_stat`
*Testing:*
Ran benchmarks on AMD milan and genoa family instances and compared output to results generated by [perfrunbook](https://github.com/aws/aws-graviton-getting-started/tree/main/perfrunbook/utilities) and Intel/graviton based instances.
Example of ipc comparison between perfrunbook and aperf:
Note: We observed some incorrect data presumably from event multiplexing (up to 13 groups of 14 events). Values may be different than true counts due to this scaling, but trends remain accurate.
> Add AMD PMC/U support

- src/data/java_profile.rs
- src/data/perf_stat.rs
- Java profile now copies instead of moving the flamegraph files from the temp directory to the record directory. This makes aperf the owner of the file.
- Reformatted PMU module imports.
*Testing:*
Ran on AMD instances and checked for perf_stat collecting events. Profiled JVMs and verified ownership matches the user who ran aperf.
> missed changes: copy temp files instead of move, crate use formatting

- src/bin/aperf.rs
- src/data.rs
- src/data/flamegraphs.rs
- src/data/java_profile.rs
- src/data/perf_profile.rs
- src/data/perf_stat.rs
- src/data/processes.rs
- src/html_files/aperf_run_stats.ts
- src/lib.rs
- src/record.rs
- src/report.rs
- src/visualizer.rs
- tests/test_aperf.rs
This uses the TempDir crate to generate unique temp directories for aperf runs. Also, move to using references where possible for the Data trait.
> Create a tmp directory for record and report

- build.rs
Add error message to compile when Node is missing
---
The message:
```
Compiling aperf v0.1.0 (/fsx/lrbison/code/aperf)
error: failed to run custom build command for `aperf v0.1.0 (/fsx/lrbison/code/aperf)`
Caused by:
process didn't exit successfully: `/fsx/lrbison/code/aperf/target/debug/build/aperf-d4acbb2dac42850a/build-script-build` (exit status: 1)
--- stdout
cargo:rustc-env=VERGEN_GIT_SHA=c88030f
cargo:rerun-if-changed=.git/HEAD
cargo:rerun-if-changed=.git/refs/heads/build
cargo:rerun-if-changed=build.rs
cargo:rerun-if-env-changed=VERGEN_IDEMPOTENT
cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH
cargo:rerun-if-changed=package.json
cargo:rerun-if-changed=package-lock.json
Build requires npm, but it was not found.  Please install Node >= 16.16.0
```
---
By …
> Add error message to compile when Node is missing

- README.md
Update the README with the documentation for the custom-pmu subtool. Also update `aperf record` with the new `--pmu-config` flag.
> CustomPMU: Update README documentation

- src/data/utils.rs
- src/lib.rs
- src/report.rs
- tests/test_aperf.rs
There is a bug in the report generation if the user collected record data with a run name containing `.`. In such cases, the report generator, since it was using file_stem(), would incorrectly create the report directory and tarball with different names.
To prevent this, use file_name() and a check to remove '.tar.gz' suffix. Also, move to using file_name() instead of file_stem() wherever needed.
[2dots.in.name.tar.gz](https://github.com/user-attachments/files/18832028/2dots.in.name.tar.gz)
> Report: Fix issue with '.' in run names

- Cargo.toml
These options allow us to reduce the size of the binary by ~45%. These do not adversely impact the speed of aperf execution.
Original binary size: 20MB
New binary size: 11MB
> Aperf: Add build options for Release profile

- src/data/perf_stat.rs
- src/html_files/analytics.ts
- src/html_files/perf_stat.ts
- src/html_files/utils.ts
This will be followed by infrastructure for other data types.
> Report: Add infrastructure for Perf Stat rules

- src/html_files/index.ts
- src/html_files/kernel_config.ts
The Kernel Config would only look at the first level entries when diffing between runs. Fix this by including all entries at all levels.
Also, change diff view to 'No' if the number of runs is 1. Create a new member to hold the choice for each datatype.
[aperf_report_custompmu_linuxbuild.tar.gz](https://github.com/user-attachments/files/19232917/aperf_report_custompmu_linuxbuild.tar.gz)
> Report: Fix bug in Kernel Config diff

- src/data/aperf_stats.rs
- src/data/diskstats.rs
- src/data/meminfodata.rs
- src/data/netstat.rs
- src/data/perf_stat.rs
- src/data/vmstat.rs
- src/html_files/analytics.ts
- src/html_files/aperf_run_stats.ts
- src/html_files/disk_stats.ts
- src/html_files/meminfo.ts
- src/html_files/netstat.ts
- src/html_files/vmstat.ts
- src/utils.rs
Rule writers can start writing rules in the corresponding data type. We are onboarding Netstat, Vmstat, Diskstat, AperfStat, 
[aperf_report_onboarded.tar.gz](https://github.com/user-attachments/files/19393449/aperf_report_onboarded.tar.gz)
> Report: Onboard more datatypes for Analytics

- src/record.rs
Check interval and period passed by the user and:
- If `interval >= period`: an error is logged and the program exits with a clear message.
- If `interval < period`: the program proceeds as normal.
Used return Err(()):
- For conditions where program is exiting with an error, used return Err(()) instead of return Ok(()) which better describes the exit with an error.
- eg. Interval>=Period
dev-dsk-parthnk-1d-70bda464 % ./target/release/aperf record --interval 10
[2025-05-30T21:42:03Z ERROR aperf::record] The overall recording period of 10 seconds needs to be longer than the interval of 10 seconds.Please increase the overall recording period or decrease the interval.
Error: Cannot start recording with the given parameters.
By submitting this pull request, I confirm that you can use, modify, …
> Fix interval period check

- src/html_files/cpu_utilization.ts
This adds IOWait CPU time to the aggregate CPU utilization graph.
Tested with local Aperf profiles. 
Here's an example CPU utilization graph for IOWait:
And this is what the aggregate CPU utilization graph looks like with this change:
> Add IOWait CPU time to aggregate CPU utilization graph.

- README.md
- src/data.rs
- src/data/perf_profile.rs
- src/lib.rs
- src/record.rs
- tests/test_aperf.rs
*Issue #, if available:*
Default 99 mayn't be needed for larger runs so giving an option helps. 
Enable an option to overide default 99
> Enable perf_frequency command line option.

- .github/workflows/repo-sync.yml
*Issue #, if available:*
This change aims to use the [repo-sync](https://github.com/repo-sync/repo-sync) tool to keep the two repos in sync
Following the instructions listed in the [repo-sync's official guide](https://github.com/repo-sync/repo-sync/blob/master/README.md), as well as [the actual implementation in the GitHub Docs repo](https://github.com/github/docs/blob/main/.github/workflows/repo-sync.yml), to create the `repo-sync.yml` file that defines the sync workflow:
* It runs once per day (we can change it to a higher frequency if needed)
* When new changes had been made to a repo before a run, it publishes and merges a PR
The commit history, including each commit's SHA, of the two repos will be kept exactly the same.
The secrets used by the workflow will …
> Create repo-sync.yml to enable repo-sync between repos

- .github/workflows/repo-sync.yml
*Issue #, if available:*
The logic of closing all existing PRs prevents contributing directly to main through a PR.
Remove the logic of closing all existing PRs in the repo-sync workflow. It will only compare the source and target branches, raise a new PR, and merges it in.
> Remove the logic of closing existing PRs in the repo-sync workflow

- .gitignore
- README.md
- src/bin/aperf.rs
- src/data.rs
- src/data/flamegraphs.rs
- src/data/perf_profile.rs
- src/html_files/aperf_runlog.ts
- src/html_files/aperf_stats.ts
- src/html_files/configure.ts
- src/html_files/cpu_utilization.ts
- src/html_files/diskstats.ts
- src/html_files/flamegraphs.ts
- src/html_files/hotline.ts
- src/html_files/interrupts.ts
- src/html_files/kernel_config.ts
- src/html_files/meminfo.ts
- src/html_files/netstat.ts
- src/html_files/perf_profile.ts
- src/html_files/perf_stat.ts
- src/html_files/processes.ts
- src/html_files/sysctl.ts
- src/html_files/systeminfo.ts
- src/html_files/utils.ts
- src/html_files/vmstat.ts
- src/lib.rs
- src/pmu.rs
- src/record.rs
- src/report.rs
- src/visualizer.rs
- tests/test_aperf.rs
Mirroring internal CR 212108965
* added the `--dont-collect` and `--collect-only` flags to allow users to select what performance data to select.
* reformatted the help menu by setting `help_heading` for each flag, which groups the flags into sections in the help menu
* remodeled the cases when data is not available:
* an error is thrown when invoking `get_data` method on an unavailable data
* upstream is expected to check if data is available before calling `get_data`
* added Typescript function `handleNoData()` that inserts the "No data collected" message into the report, if the run data is empty
* Revamped the help menu and README (for the new README, see https://github.com/CongkaiTan/aperf/blob/53d9684d58df0b844b236be89e6ebfb0e944e9b6/README.md)
Below is the new `aperf record -h` …
> Add --dont-collect and --collect-only flags to customize which data to collect
